import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  const foo = 'asdf';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by cr asdf sdafas df asd fadsfas dfa dfads a f s faf asdfa dsf ads sfa fdsf asfdsasfds asfds dafads fdsafs fa sdf eate next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to {foo} <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </>
  );
};

export default Home;
